<?php


namespace App\Http\Constant;


class MessageConstant
{
    const MESSAGE_SUCCESS = "操作成功";
    const MESSAGE_FAILURE = "操作失败";
    const MESSAGE_VALIDATOR_USERNAME_LENTH_MIN = "用户名长度不得小于5个字符";
    const MESSAGE_VALIDATOR_USERNAME_LENTH_MAX = "用户名长度不得大于30个字符";
    const MESSAGE_VALIDATOR_PASSWD_LENTH_MIN = "密码不得为空字符";
    const MESSAGE_VALIDATOR_VCODE_LENTH = "验证码长度有误";
    const MESSAGE_VALIDATOR_VCODE_ERROR = "验证码错误";
    const MESSAGE_VALIDATOR_VCODE_EXPRIED_ERROR = "验证码已过期";
    const MESSAGE_VALIDATOR_VCODE_KEYID_EMPTY = "请正确操作";
    const MESSAGE_MEMBERS_NOT_EXIST = "用户名不存在或账户已过期";
    const MESSAGE_MEMBERS_WRONG_PASSWD = "密码错误";
    const MESSAGE_LOGIN_SUCCESS = "登陆成功";
    const MESSAGE_LOGIN_FAILURE = "登陆失败";
    const MESSAGE_LOGIN_EXPIRED = "登陆过期";
    const MESSAGE_LOGOUT_SUCCESS = "退出成功";
    const MESSAGE_USER_STATUS_IS_SETTING = "状态已设置";
    const MESSAGE_USER_STATUS_IS_FAILURE = "状态设置失败";
    const MESSAGE_MEMBERS_PASSWD_NOT_SAME = "2次输入密码不一致";
    const MESSAGE_MEMBERS_PASSWD_NOT_EMPTY = "密码或确认密码不能为空";
    const MESSAGE_MEMBERS_PASSWD_EDIT_SUCCESS = "密码修改成功";
    const MESSAGE_MEMBERS_PASSWD_EDIT_FAILURE = "密码修改失败";
    const MESSAGE_USER_SELECTED_CHECKBOX = "请勾选数据";

    const MESSAGE_SUCCESS_CODE = 0;
    const MESSAGE_FAILURE_CODE = 10000;
    const MESSAGE_LOGIN_FALID_CODE = 1001;
    const MESSAGE_VALIDATOR_USERNAME_LENTH_MIN_CODE = 10001;
    const MESSAGE_VALIDATOR_USERNAME_LENTH_MAX_CODE = 10002;
    const MESSAGE_VALIDATOR_PASSWD_LENTH_MIN_CODE = 10003;
    const MESSAGE_VALIDATOR_VCODE_LENTH_CODE = 10004;
    const MESSAGE_VALIDATOR_VCODE_ERROR_CODE = 10005;
    const MESSAGE_VALIDATOR_VCODE_EXPRIED_ERROR_CODE = 10006;
    const MESSAGE_VALIDATOR_VCODE_KEYID_EMPTY_CODE = 10007;
    const MESSAGE_MEMBERS_NOT_EXIST_CODE = 10008;
    const MESSAGE_MEMBERS_WRONG_PASSWD_CODE = 10009;
    const MESSAGE_LOGIN_FAILURE_CODE = 10010;
    const MESSAGE_LOGIN_EXPIRED_CODE = 10011;
    const MESSAGE_USER_STATUS_IS_FAILURE_CODE = 10012;
    const MESSAGE_MEMBERS_PASSWD_NOT_SAME_CODE = 10013;
    const MESSAGE_MEMBERS_PASSWD_NOT_EMPTY_CODE = 10014;
    const MESSAGE_MEMBERS_PASSWD_EDIT_SUCCESS_CODE = 10015;
    const MESSAGE_MEMBERS_PASSWD_EDIT_FAILURE_CODE = 10016;
    const MESSAGE_USER_SELECTED_CHECKBOX_CODE = 10017;


}
